# Generated by Django 5.2.12 on 2026-04-08 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='Mô tả của người dùng')),
                ('refined_prompt', models.TextField(blank=True, help_text='Mô tả đã được AI tối ưu', null=True)),
                ('image', models.ImageField(blank=True, upload_to='ai_generated/%Y/%m/%d/')),
                ('model_name', models.CharField(default='dall-e-3', max_length=100)),
                ('resolution', models.CharField(default='1024x1024', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Công khai ảnh này với mọi người')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
